### ISSUE TITLE
Duplicate mappings when copyResources

### ISSUE THREAD

**Issue by hepin1989** [henrikerola/sbt-vaadin-plugin#13]
```
[info] Compiling theme 'tests-valo-metro'
[info] Compiling theme 'tests-valo-facebook'
[info] Compiling theme 'tests-valo-flatdark'
[info] Compiling theme 'tests-valo-dark'
[info] Compiling theme 'tests-valo-reindeer'
[info] Compiling theme 'tests-valo-flat'
[info] Compiling theme 'tests-valo-light'
[info] Compiling theme 'tests-valo-blueprint'
[trace] Stack trace suppressed: run last gm-tools/compile:copyResources for the full output.
[error] (gm-tools/compile:copyResources) Duplicate mappings:
[error] 	/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css
[error] from
[error] 	/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-reindeer/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-blueprint/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-metro/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flatdark/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-dark/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-light/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flat/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-facebook/styles.css
[error] Total time: 22 s, completed 2015-12-30 20:29:09
```

and the details is :
```
> last gm-tools/compile:copyResources 
[debug] Copy resource mappings: 
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-metro/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-facebook/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flatdark/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-dark/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-reindeer/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flat/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-light/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
[debug] 	(/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-blueprint/styles.css,/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css)
java.lang.RuntimeException: Duplicate mappings:
	/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css
from
	/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-reindeer/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-blueprint/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-metro/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flatdark/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-dark/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-light/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flat/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo/styles.css
		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-facebook/styles.css
	at scala.sys.package$.error(package.scala:27)
	at sbt.Sync$.noDuplicateTargets(Sync.scala:67)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:25)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:22)
	at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:891)
	at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:887)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (gm-tools/compile:copyResources) Duplicate mappings:
[error] 	/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/target/classes/styles.css
[error] from
[error] 	/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-reindeer/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-blueprint/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-metro/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flatdark/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-dark/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-light/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-flat/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo/styles.css
[error] 		/home/kerr/devProject/ideaProject/Qgame-wui/stack/gm-tools/src/main/webapp/VAADIN/themes/tests-valo-facebook/styles.css
> 

```

**Comment by henrikerola** [comment]
Hi, thanks for reporting this.

Any example on how this happens?

**Comment by hepin1989** [comment]
@henrikerola  thanks
https://github.com/hepin1989/QGameWUItest
```
[trace] Stack trace suppressed: run last gm-tools/compile:copyResources for the full output.
[error] (gm-tools/compile:copyResources) Duplicate mappings:
[error] 	/home/kerr/QGameWUItest/stack/gm-tools/target/scala-2.11/classes/styles.css
[error] from
[error] 	/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-flatdark/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-reindeer/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-flat/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-light/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-metro/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-blueprint/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-dark/styles.css
[error] 		/home/kerr/QGameWUItest/stack/gm-tools/target/webapp/VAADIN/themes/tests-valo-facebook/styles.css
[error] Total time: 15 s, completed 2015-12-31 11:57:38

```

**Comment by 0x01110000** [comment]
I got the same problem when using a Vaadin addon which provides its own style.scss.

Removing the addon from the widgetset resolves the error. The addon won't work anymore though.
